import { auth } from '@/auth'
import { prisma } from '@/lib/db'
import { NextResponse } from 'next/server'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import { format } from 'date-fns'

function formatNaira(kobo: bigint): string {
  return `₦${(Number(kobo) / 100).toLocaleString('en-NG', { minimumFractionDigits: 0 })}`
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const session = await auth()
  const userId = (session?.user as { id?: string })?.id
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const payment = await prisma.payment.findUnique({
    where: { id },
    include: {
      deal: {
        include: { parties: { select: { userId: true } } },
      },
    },
  })
  if (!payment) return NextResponse.json({ error: 'Payment not found' }, { status: 404 })

  const isCreator = payment.deal.createdById === userId
  const isParty = payment.deal.parties.some((p) => p.userId === userId)
  if (!isCreator && !isParty) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  if (payment.status !== 'paid') {
    return NextResponse.json({ error: 'Receipt only available for paid payments' }, { status: 400 })
  }

  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)
  const page = doc.addPage([595, 842])
  const { width } = page.getSize()
  let y = 780

  const coral = rgb(0.94, 0.39, 0.31)
  const dark = rgb(0.1, 0.12, 0.18)
  const gray = rgb(0.4, 0.42, 0.45)
  const lightGray = rgb(0.85, 0.86, 0.88)

  // Header bar
  page.drawRectangle({ x: 0, y: 792, width: 595, height: 50, color: coral })
  page.drawText('SignNest', {
    x: 50, y: 808, size: 22, font: fontBold, color: rgb(1, 1, 1),
  })
  page.drawText('Payment Receipt', {
    x: 400, y: 810, size: 12, font, color: rgb(1, 1, 1),
  })

  // Receipt number
  y -= 10
  page.drawText('RECEIPT', { x: 50, y, size: 28, font: fontBold, color: dark })
  y -= 25
  page.drawText(`#${payment.id.slice(0, 8).toUpperCase()}`, {
    x: 50, y, size: 12, font, color: gray,
  })

  // Divider
  y -= 30
  page.drawLine({
    start: { x: 50, y }, end: { x: width - 50, y },
    thickness: 1, color: lightGray,
  })

  // Deal info section
  y -= 30
  page.drawText('Deal', { x: 50, y, size: 10, font, color: gray })
  y -= 18
  page.drawText(payment.deal.title, { x: 50, y, size: 13, font: fontBold, color: dark })
  y -= 18
  page.drawText(payment.deal.propertyAddress, { x: 50, y, size: 10, font, color: gray })

  // Payment details section
  y -= 40
  page.drawLine({
    start: { x: 50, y }, end: { x: width - 50, y },
    thickness: 1, color: lightGray,
  })
  y -= 25

  const rows: [string, string][] = [
    ['Description', payment.description],
    ['Amount', formatNaira(payment.amount)],
    ['Currency', payment.currency],
    ['Payment Method', payment.method ?? '—'],
    ['Reference', payment.reference ?? '—'],
    ['Date Paid', payment.paidAt ? format(payment.paidAt, 'dd MMMM yyyy, HH:mm') : '—'],
    ['Status', 'PAID'],
  ]

  for (const [label, value] of rows) {
    page.drawText(label, { x: 50, y, size: 10, font, color: gray })
    page.drawText(value, { x: 250, y, size: 11, font: fontBold, color: dark })
    y -= 24
  }

  // Amount highlight
  y -= 15
  page.drawRectangle({
    x: 50, y: y - 10, width: width - 100, height: 50,
    color: rgb(0.98, 0.95, 0.93),
    borderColor: coral, borderWidth: 1,
  })
  page.drawText('Total Paid', { x: 70, y: y + 18, size: 11, font, color: gray })
  page.drawText(formatNaira(payment.amount), {
    x: 70, y: y - 2, size: 20, font: fontBold, color: coral,
  })

  // Footer
  y -= 70
  page.drawLine({
    start: { x: 50, y }, end: { x: width - 50, y },
    thickness: 1, color: lightGray,
  })
  y -= 20
  page.drawText('This is a computer-generated receipt and does not require a signature.', {
    x: 50, y, size: 8, font, color: gray,
  })
  y -= 14
  page.drawText(`Generated by SignNest on ${format(new Date(), 'dd MMM yyyy HH:mm:ss')}`, {
    x: 50, y, size: 8, font, color: gray,
  })

  const pdfBytes = await doc.save()

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="receipt-${payment.id.slice(0, 8)}.pdf"`,
    },
  })
}
